version: '3.8'

services:
  # --- DATABASES (One container per service) ---

  mysql-product:
    image: mysql:8.0
    container_name: mysql-product
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    ports:
      - "3306:3306"
    volumes:
      - product-db-data:/var/lib/mysql
    networks:
      - iae-network

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
    ports:
      - "3307:3306"
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - iae-network

  mysql-stock:
    image: mysql:8.0
    container_name: mysql-stock
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_db
    ports:
      - "3308:3306"
    volumes:
      - stock-db-data:/var/lib/mysql
    networks:
      - iae-network

  mysql-shipping:
    image: mysql:8.0
    container_name: mysql-shipping
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipping_db
    ports:
      - "3309:3306"
    volumes:
      - shipping-db-data:/var/lib/mysql
    networks:
      - iae-network

  # --- SERVICES ---

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "8001:8000"
    env_file:
      - ./services/product-service/.env
    depends_on:
      - mysql-product
    networks:
      - iae-network

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "8002:8000"
    env_file:
      - ./services/order-service/.env
    depends_on:
      - mysql-order
    networks:
      - iae-network

  stock-service:
    build: ./services/stock-service
    container_name: stock-service
    ports:
      - "8003:8000"
    env_file:
      - ./services/stock-service/.env
    depends_on:
      - mysql-stock
    networks:
      - iae-network

  shipping-service:
    build: ./services/shipping-service
    container_name: shipping-service
    ports:
      - "8004:8000"
    env_file:
      - ./services/shipping-service/.env
    depends_on:
      - mysql-shipping
    networks:
      - iae-network

volumes:
  product-db-data:
  order-db-data:
  stock-db-data:
  shipping-db-data:


networks:
  iae-network:
    driver: bridge
